#!/usr/bin/env ruby
# encoding: utf-8

require 'nokogiri'
require_relative 'playlist_downloader'

template = 
<<-eos
<?xml version="1.0" encoding="utf-8"?>
<playlist version="1" xmlns="http://xspf.org/ns/0/">
<trackList>
<track>
<title>%s</title>
<artist>%s</artist>
</track>
</trackList>
</playlist>
eos

Dir['misc/*'].each do |file|
	next unless File.extname(file) == '.mp3'

	puts "文件：#{file}"

	print '歌名：'
	title = gets.strip

	title = File.basename(file, File.extname(file)) if title.empty?

	print '歌手：'
	artist = gets.strip

	info = Nokogiri::XML(template % [title, artist])

	puts "# 歌名：#{title}\n# 歌手：#{artist}"

	puts info

	PlaylistDownloader.write_info(file, info, 'resources/Favorites.png')
end